# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://$MQTT_BROKER_HOST:1883/"]
username="chirpstack"
password=$CHIRPSTACK_MQTT_PWD

[integration.mqtt]
# event_topic_template="eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
# state_topic_template="eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
# command_topic_template="eu868/gateway/{{ .GatewayID }}/command/#"
event_topic_template="gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="gateway/{{ .GatewayID }}/command/#"
